# 提交新订单
POST {{host}}/orders
Content-Type: application/json

{
  "ownerId": "roc",
  "recipientId": "1234567",
  "items": [
    {
      "goodsId": 1,
      "quantity": 1
    },
    {
      "goodsId": 2,
      "quantity": 2
    }
  ]
}

###

# 发起付款
GET {{host}}/orders/1434534943584817152/payment

###

# 付款成功
POST {{host}}/payments/1434751300108685312

###

# 订单打包
POST {{host}}/packages?orderId=1434534943584817152

###
