# 提交新订单
POST {{host}}/orders
Content-Type: application/json

{
  "ownerId": "roc",
  "recipientId": "1234567",
  "items": [
    {
      "goodsId": 1,
      "quantity": 3
    },
    {
      "goodsId": 2,
      "quantity": 1
    }
  ]
}

###

# 发起付款
GET {{host}}/orders/{{orderId}}/payment

###

# 付款成功
POST {{host}}/payments/1435172442178981888

###

# 订单打包
POST {{host}}/packages?orderId={{orderId}}

###

# 订单发货
PUT {{host}}/packages/{{packageId}}/delivering
Content-Type: application/json

{
  "expressNo": "123456678"
}

###

# 订单签收
PUT {{host}}/packages/{{packageId}}/signing
Content-Type: application/json

###

# 订单取消
DELETE {{host}}/orders/{{orderId}}
Content-Type: application/json

###